import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    include: ['tests/**/*.test.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      include: ['src/**/*.ts'],
      exclude: [
        'src/**/*.d.ts',
        'src/_archived/**',
        'src/db/**',
        'src/index.ts',
        'src/routes/admin.ts',
        'src/routes/billing.ts',
        'src/routes/analytics.ts',
        'src/routes/health.ts',
        'src/routes/dashboard.ts',
        'src/routes/static.ts',
        'src/routes/webhooks.ts',
        'src/routes/audio.ts',
        'src/services/analytics.ts',
        'src/services/stripe.ts',
        'src/services/monitoring.ts',
        'src/services/storage.ts',
        'src/services/edgeTTS.ts',
        'src/middleware/admin.ts',
        'src/middleware/security.ts',
        'src/middleware/tierCheck.ts',
        'src/middleware/validation.ts',
        'src/middleware/rateLimit.ts',
        'src/middleware/requestLogger.ts',
        'src/middleware/index.ts',
        'src/lib/hypr-*.ts',
        'src/lib/index.ts',
        'src/utils/index.ts',
      ],
      thresholds: {
        lines: 60,
        functions: 55,
        branches: 50,
        statements: 60,
      },
    },
    setupFiles: ['tests/setup.ts'],
    testTimeout: 10000,
    hookTimeout: 10000,
  },
});
